main: 'fr.multimc.api.spigot.ServerApi'
name: 'MultiMC-API'
softdepend:
  - WorldEdit
  - UltimateAdvancementAPI

version: '1.10.2-SNAPSHOT'
api-version: '1.19'

authors: [ 'Loïc MAES', 'Tom CZEKAJ' ]
description: 'Manage a game tournament server.'

commands:
  relativeto:
    description: Set the relative position of a player.
    usage: /relativeto <x> <y> <z>
    permission: fr.multimc.api.commands.relativeto
  start-mmc:
    description: Start instances
    permission: fr.multimc.api.commands.start-mmc
  stop-mmc:
    description: Stop instances
    permission: fr.multimc.api.commands.stop-mmc
  mmc-debug:
    description: Debug command
    permission: fr.multimc.api.commands.mmc-debug

permissions:
  fr.multimc.api.*:
    children:
      fr.multimc.api.commands.*: true
  fr.multimc.api.commands.*:
    children:
      fr.multimc.api.commands.relativeto: true
      fr.multimc.api.commands.start-mmc: true
      fr.multimc.api.commands.stop-mmc: true
      fr.multimc.api.commands.mmc-debug: true
  fr.multimc.api.commands.relativeto:
    description: Give relative position from a given point.
    default: op
  fr.multimc.api.commands.start-mmc:
    description: Start instances
    default: op
  fr.multimc.api.commands.stop-mmc:
    description: Stop instances
    default: op
  fr.multimc.api.commands.mmc-debug:
    description: Debug command
    default: op
